export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const GET_ASST_START = "GET_ASST_START";
export const GET_ASST_SUCCESS = "GET_ASST_SUCCESS";
export const GET_ASST_FAIL = "GET_ASST_FAIL";

export const GET_ASST_DETAIL_START = "GET_ASST_DETAIL_START";
export const GET_ASST_DETAIL_SUCCESS = "GET_ASST_DETAIL_SUCCESS";
export const GET_ASST_DETAIL_FAIL = "GET_ASST_DETAIL_FAIL";

export const CREATE_ASST_START = "CREATE_ASST_START";
export const CREATE_ASST_SUCCESS = "CREATE_ASST_SUCCESS";
export const CREATE_ASST_FAIL = "CREATE_ASST_FAIL";

export const GET_GRADED_ASST_START = "GET_GRADED_ASST_START";
export const GET_GRADED_ASST_SUCCESS = "GET_GRADED_ASST_SUCCESS";
export const GET_GRADED_ASST_FAIL = "GET_GRADED_ASST_FAIL";

export const CREATE_GRADED_ASST_START = "CREATE_GRADED_ASST_START";
export const CREATE_GRADED_ASST_SUCCESS = "CREATE_GRADED_ASST_SUCCESS";
export const CREATE_GRADED_ASST_FAIL = "CREATE_GRADED_ASST_FAIL";
export const CREATE_GRADED_ASST_FINISH = "CREATE_GRADED_ASST_FINISH";
